version: 2
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha
  environment:
    JVM_OPTS: -Xmx3200m
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: build sample
          command: ./gradlew build -PpreDexLibraries=false
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  check:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-check-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Check
          command: ./gradlew check -PpreDexLibraries=false
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-check-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
#Workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - check